name: Build Windows Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Build Electron app
      run: |
        npm run electron-build-win

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: electron-build
        path: dist/
