name: Build Windows Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Debug GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}"

    - name: Set GH_TOKEN environment variable
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

    - name: Build Electron app
      run: |
        npm run electron-build-win
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 确保传递 GH_TOKEN 给 electron-builder

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: electron-build
        path: dist/
